
# Change these first
owner: monitoring-apps # Your GitHub organization or username, where this repository lives
repo: qc.app # The name of this repository

sites:
  - name: Quirk Club Institutional
    url: https://quirkclub.io
    icon: https://quirkclub-dev.web.app/assets/icon/quirk-icons/logo-160x160.png #TODO: change url.
  - name: Quirk Club Argentina
    url: https://quirkclub.app
    icon: https://quirkclub-dev.web.app/assets/icon/quirk-icons/logo-160x160.png #TODO: change url.
    maxResponseTime: 5000
  - name: Quirk Club Argentina (API endpoint)
    method: POST
    url: https://us-central1-quirkclub-dev.cloudfunctions.net/api/check/api
    headers:
      - "api-key: $API_KEY"
    icon: https://quirkclub-dev.web.app/assets/icon/quirk-icons/notifications/tv-monitor.svg
    maxResponseTime: 5000
  - name: Quirk Club Argentina (Payment Gateway)
    method: POST
    url: https://us-central1-quirkclub-dev.cloudfunctions.net/api/check/payment-gateway-ml
    headers:
      - "api-key: $API_KEY"
    icon: https://quirkclub-dev.web.app/assets/icon/quirk-icons/notifications/credit-card.svg
    maxResponseTime: 5000
  - name: Quirk Club Argentina (SSR)  
    url: https://quirkclub-dev.web.app/ssr-check
    __dangerous__body_down: "<title>QuirkClub</title>"
    
    
status-website:
  theme: ocean
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.quirkclub.io
  # baseUrl: /qc.app
  name: Quirk Club
  logoUrl: https://quirkclub-dev.web.app/assets/icon/quirk-icons/logo-160x160.png
  icon: https://quirkclub-dev.web.app/assets/icon/quirk-icons/logo-160x160.png #TODO: change url.
  introTitle: "**Quirk Club** status."
  introMessage: Quirk club status page which uses **real-time** data.
  favicon: https://quirkclub-dev.web.app/assets/icon/favicon.png
  navbar:
    - title: Quirk Club - Institutional
      href: https://quirkclub.io
    - title: Quirk Club - Argentina
      href: https://quirkclub.app
      #href: https://ar.quirkclub.app
#    - title: GitHub
#      href: https://github.com/$OWNER/$REPO
